version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm login && npm install --omit=dev
  pre_build:
    commands:
      - echo Pre-Build started on `date`, Installing NPM Dependencies
  build:
    commands:
      - echo Build started on `date`
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - "**/*"
